website/auth.py
from datetime import datetime
from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify,session
from .models import User, Review
from werkzeug.security import generate_password_hash, check_password_hash
from . import db   ##means from __init__.py import db
from flask_login import login_user, login_required, logout_user, current_user
from .forms import PasswordResetRequestForm, PasswordResetForm, LoginForm, SignupForm  
import secrets
from flask_mail import Mail, Message
from .mail import mail
import time
import random
from flask_wtf.csrf import CSRFError
import json
from email_validator import validate_email, EmailNotValidError
from werkzeug.utils import secure_filename
import os
from flask import current_app



auth = Blueprint('auth', __name__)
@auth.route('/login', methods=['GET', 'POST'])
def login():
    if not current_user.is_authenticated:
        if request.method == 'POST':
            email = request.form.get('email')
            password = request.form.get('password')
            remember_me = request.form.get('remember_me') == 'on'
            user = User.query.filter_by(email=email.lower()).first()
            if user:
                if check_password_hash(user.password, password):
                    flash('Logged in successfully!', category='success')
                    login_user(user, remember=remember_me)
                    # Check if there is a stored URL in the session
                    next_url = session.get('next_url')
                    if next_url:
                        # Redirect the user to the stored URL
                        return redirect(next_url)
    
                    # If there's no stored URL, redirect to the default page
                    return redirect(url_for('lib.library_redirect'))
                else:
                    flash('Email or password is incorrect, try again.', category='error')
            else:
                flash('Email or password is incorrect, try again.', category='error')
    
        # Store the URL the user came from in the session
        session['next_url'] = request.referrer
    
        return render_template("login.html", user=current_user)
    else:
        return redirect(url_for('views.home'))


@auth.route('/login_popup/', methods=['POST'])
def login_popup():
    response_data = {'success': False, 'message': ''}
    request_data = json.loads(request.data)
    if request_data:
        email = request_data.get('email')
        password = request_data.get('password')
        
        user = User.query.filter_by(email=email.lower()).first()
        if user:
            if check_password_hash(user.password, password):
                login_user(user, remember=True)
                response_data['success'] = True
                response_data['message'] = 'Logged in successfully!'
            else:
                response_data['message'] = 'Email or password is incorrect, try again.'
        else:
            response_data['message'] = 'Email or password is incorrect, try again.'
    else:
        response_data['message'] = 'Invalid request data.'

    return jsonify(response_data)


@auth.route('/login_form', methods=['GET'])
def login_form():
   
    return render_template('login_register_modal.html')


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('views.home'))

# User Profiles
@auth.route('/user_profile/', methods=['GET'])
@login_required
def myprofile_redirect():
    # Redirect the user to their own profile page
    return redirect(url_for('auth.profile', user_id=current_user.id))

# User Profiles
@auth.route('/user_profile/<int:user_id>', methods=['GET', 'POST'])
@login_required
def profile(user_id):
    if user_id == current_user.id:
        if request.method == 'POST':
            recentBio = request.form.get('thoughts')
            if not recentBio:
                field_mapping = {
                    'first_name': 'first_name',
                    'email': 'email',
                    'education': 'education',
                    'f_of_Study': 'f_of_Study',
                }
                values = {}
                for form_field, db_field in field_mapping.items():
                    form_value = request.form.get(form_field)
                    if form_field == 'email':
                        if form_value:
                            try:
                                # Validate the email format
                                valid = validate_email(form_value)
                                form_value = valid["email"]
                            except EmailNotValidError as e:
                                flash('Invalid email format!', category='error')
                                return redirect(request.url)
                            # Check if the email already exists in the database
                            existing_user = User.query.filter_by(email=form_value).first()
                            if existing_user is not None and existing_user != current_user:
                                flash('Email already exists for another user!', category='error')
                                return redirect(request.url)
                        else:
                            flash('Email is required!', category='error')
                            return redirect(request.url)
                    if form_value:
                        values[db_field] = form_value
    
                if values:
                    # Update the user's information in the database
                    User.query.filter_by(id=current_user.id).update(values)
                    db.session.commit()
                    return redirect(url_for('auth.profile', user_id=current_user.id))
                    flash('User info updated!', category='success')
            if recentBio:
                new_review = Review(
                    date=datetime.now(),
                    bio=str(recentBio),
                    user_id=current_user.id
                )
                db.session.add(new_review)
                db.session.commit()
                return redirect(url_for('auth.profile', user_id=current_user.id))
                flash('Note added!', category='success')
        last_review = Review.query.filter_by(user_id=current_user.id).order_by(Review.date.desc()).first()
        reviews = Review.query.filter_by(user_id=current_user.id).all()
        num_of_reviews = sum(1 for review in reviews if review.data)
        return render_template("profile.html", User=current_user, LastReview=last_review,numofRev=num_of_reviews)
    else:
        flash('You do not have access to this profile!', category='error')
        return redirect(url_for('views.home'))
        
def allowed_file(filename):
    allowed_extensions = current_app.config.get('ALLOWED_EXTENSIONS')
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in allowed_extensions
@auth.route('/update_av/<int:user_id>', methods=['POST'])
@login_required
def upload_avatar(user_id):
    if 'avatar' not in request.files:
        return redirect(request.url)
    file = request.files['avatar']
    if file.filename == '':
        return redirect(request.url)
    if file and allowed_file(file.filename):
        filename = secure_filename(file.filename)
        # Define the upload folder and ensure it exists
        upload_folder = current_app.config['UPLOAD_FOLDER']
        if not os.path.exists(upload_folder):
            os.makedirs(upload_folder)
        file.save(os.path.join(upload_folder, filename))
        photo_path = 'assets/' + filename
        # Get the user to update
        user = User.query.get(user_id)
        user.photo = photo_path
        db.session.commit()
        flash('Updated successfully', 'success')
        return redirect(url_for('auth.profile', user_id=current_user.id))

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    # Generate random numbers for the math question
    num1 = random.randint(1, 10)
    num2 = random.randint(1, 10)
    # Calculate the answer
    answer = num1 + num2
    # Generate a random string for the input field's id attribute
    random_id = ''.join(random.choice("abcdefghijklmnopqrstuvwxyz0123456789") for _ in range(10))
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        education = request.form.get('Education')
        f_of_Study = request.form.get('Acinterest')
        userAnswer = int(request.form.get('captcha-answer'))

        
        if not education:
            education = 'Edit in Profile'
        if not f_of_Study:
            f_of_Study = 'Edit in Profile'

        user = User.query.filter_by(email=email.lower()).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        elif userAnswer != answer:
            flash('Wrong Captcha Answer!', category='error')
        else:
            new_user = User(
                email=email.lower(),
                first_name=first_name,
                education=education,
                f_of_Study=f_of_Study,
                password=generate_password_hash(password1),
                reset_password_token=None, # Set reset_password_token to None
                reset_password_token_timestamp = None
            )
            db.session.add(new_user)
            db.session.commit()

website/src/jobspy/jobs/__init__.py
from typing import Union, Optional
from datetime import date
from enum import Enum

from pydantic import BaseModel, validator


class JobType(Enum):
    FULL_TIME = (
        "fulltime",
        "períodointegral",
        "estágio/trainee",
        "cunormăîntreagă",
        "tiempocompleto",
        "vollzeit",
        "voltijds",
        "tempointegral",
        "全职",
        "plnýúvazek",
        "fuldtid",
        "دوام كامل",
        "kokopäivätyö",
        "tempsplein",
        "vollzeit",
        "πλήρηςαπασχόληση",
        "teljesmunkaidő",
        "tempopieno",
        "tempsplein",
        "heltid",
        "jornadacompleta",
        "pełnyetat",
        "정규직",
        "100%",
        "全職",
        "งานประจำ",
        "tamzamanlı",
        "повназайнятість",
        "toànthờigian",
    )
    PART_TIME = ("parttime", "teilzeit")
    CONTRACT = ("contract", "contractor")
    TEMPORARY = ("temporary",)
    INTERNSHIP = ("internship", "prácticas", "ojt(onthejobtraining)", "praktikum")

    PER_DIEM = ("perdiem",)
    NIGHTS = ("nights",)
    OTHER = ("other",)
    SUMMER = ("summer",)
    VOLUNTEER = ("volunteer",)


class Country(Enum):
    ARGENTINA = ("argentina", "ar")
    AUSTRALIA = ("australia", "au")
    AUSTRIA = ("austria", "at")
    BAHRAIN = ("bahrain", "bh")
    BELGIUM = ("belgium", "be")
    BRAZIL = ("brazil", "br")
    CANADA = ("canada", "ca")
    CHILE = ("chile", "cl")
    CHINA = ("china", "cn")
    COLOMBIA = ("colombia", "co")
    COSTARICA = ("costa rica", "cr")
    CZECHREPUBLIC = ("czech republic", "cz")
    DENMARK = ("denmark", "dk")
    ECUADOR = ("ecuador", "ec")
    EGYPT = ("egypt", "eg")
    FINLAND = ("finland", "fi")
    FRANCE = ("france", "fr")
    GERMANY = ("germany", "de")
    GREECE = ("greece", "gr")
    HONGKONG = ("hong kong", "hk")
    HUNGARY = ("hungary", "hu")
    INDIA = ("india", "in")
    INDONESIA = ("indonesia", "id")
    IRELAND = ("ireland", "ie")
    ISRAEL = ("israel", "il")
    ITALY = ("italy", "it")
    JAPAN = ("japan", "jp")
    KUWAIT = ("kuwait", "kw")
    LUXEMBOURG = ("luxembourg", "lu")
    MALAYSIA = ("malaysia", "malaysia")
    MEXICO = ("mexico", "mx")
    MOROCCO = ("morocco", "ma")
    NETHERLANDS = ("netherlands", "nl")
    NEWZEALAND = ("new zealand", "nz")
    NIGERIA = ("nigeria", "ng")
    NORWAY = ("norway", "no")
    OMAN = ("oman", "om")
    PAKISTAN = ("pakistan", "pk")
    PANAMA = ("panama", "pa")
    PERU = ("peru", "pe")
    PHILIPPINES = ("philippines", "ph")
    POLAND = ("poland", "pl")
    PORTUGAL = ("portugal", "pt")
    QATAR = ("qatar", "qa")
    ROMANIA = ("romania", "ro")
    SAUDIARABIA = ("saudi arabia", "sa")
    SINGAPORE = ("singapore", "sg")
    SOUTHAFRICA = ("south africa", "za")
    SOUTHKOREA = ("south korea", "kr")
    SPAIN = ("spain", "es")
    SWEDEN = ("sweden", "se")
    SWITZERLAND = ("switzerland", "ch")
    TAIWAN = ("taiwan", "tw")
    THAILAND = ("thailand", "th")
    TURKEY = ("turkey", "tr")
    UKRAINE = ("ukraine", "ua")
    UNITEDARABEMIRATES = ("united arab emirates", "ae")
    UK = ("uk", "uk")
    USA = ("usa", "www")
    URUGUAY = ("uruguay", "uy")
    VENEZUELA = ("venezuela", "ve")
    VIETNAM = ("vietnam", "vn")

    # internal for ziprecruiter
    US_CANADA = ("usa/ca", "www")

    # internal for linkeind
    WORLDWIDE = ("worldwide", "www")

    def __new__(cls, country, domain):
        obj = object.__new__(cls)
        obj._value_ = country
        obj.domain = domain
        return obj

    @property
    def domain_value(self):
        return self.domain

    @classmethod
    def from_string(cls, country_str: str):
        """Convert a string to the corresponding Country enum."""
        country_str = country_str.strip().lower()
        for country in cls:
            if country.value == country_str:
                return country
        valid_countries = [country.value for country in cls]
        raise ValueError(
            f"Invalid country string: '{country_str}'. Valid countries (only include this param for Indeed) are: {', '.join(valid_countries)}"
        )


class Location(BaseModel):
    country: Country = None
    city: Optional[str] = None
    state: Optional[str] = None

    def display_location(self) -> str:
        location_parts = []
        if self.city:
            location_parts.append(self.city)
        if self.state:
            location_parts.append(self.state)
        if self.country and self.country not in (Country.US_CANADA, Country.WORLDWIDE):
            if self.country.value in ("usa", "uk"):
                location_parts.append(self.country.value.upper())
            else:
                location_parts.append(self.country.value.title())
        return ", ".join(location_parts)


class CompensationInterval(Enum):
    YEARLY = "yearly"
    MONTHLY = "monthly"
    WEEKLY = "weekly"
    DAILY = "daily"
    HOURLY = "hourly"


class Compensation(BaseModel):
    interval: CompensationInterval
    min_amount: int = None
    max_amount: int = None
    currency: Optional[str] = "USD"


class JobPost(BaseModel):
    title: str
    company_name: str
    job_url: str
    location: Optional[Location]

    description: Optional[str] = None
    job_type: Optional[JobType] = None
    compensation: Optional[Compensation] = None
    date_posted: Optional[date] = None


class JobResponse(BaseModel):
    jobs: list[JobPost] = []

website/templates/login_register_modal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login/Register Modal by Creative Tim</title>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <style>body{padding-top: 60px;}</style>
    <link href="{{ url_for('static', filename='assets/css/bootstrap.css')}}" rel="stylesheet" />
    <link href="{{ url_for('static', filename='assets/css/login-register.css')}}" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"/>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!--<script src="{{ url_for('static', filename='assets/js/jquery-1.10.2.js')}}" type="text/javascript"></script>-->
    <script src="{{ url_for('static', filename='assets/js/bootstrap.js')}}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='assets/js/login-register.js')}}" type="text/javascript"></script>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-sm-4"></div>
            <div class="col-sm-4">
                <a class="btn big-login" data-toggle="modal" href="javascript:void(0)" onclick="openLoginModal();">Log in</a>
                <a class="btn big-register" data-toggle="modal" href="javascript:void(0)" onclick="openRegisterModal();">Register</a>
            </div>
            <div class="col-sm-4"></div>
        </div>

        <div class="modal fade login" id="loginModal">
            <div class="modal-dialog login animated">
                <div class="modal-content">
                    <!-- Content for the login form -->
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Login to Related Engine</h4>
                    </div>
                    <div class="modal-body" id="loginFormContainer">
                        <div class="box">
                            <div class="content">
                                <div class="division">
                                    <div class="line l"></div>
                                    <div class="liner"></div>
                                </div>
                                <div class="error"></div>
                                <div class="form loginBox">
                                     <form method="POST" accept-charset="UTF-8">
                                        <input id="email_login" class="form-control" type="text" placeholder="Email" name="email">
                                        <input id="password_login" class="form-control" type="password" placeholder="Password" name="password">
                                        <button type="button" class="btn btn-default btn-login" onclick="loginAndHidePopup({ email: $('#email_login').val(), password: $('#password_login').val() })">Login</button>
                                    </form>

                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- End of login form content -->

                    <!-- Content for the sign-up form -->
                    <!--<div class="modal-body">-->
                    <!--    <div class="box">-->
                    <!--        <div class="content registerBox" style="display:none;">-->
                    <!--            <div class="form">-->
                    <!--                <form method="" accept-charset="UTF-8" html="{:multipart=>true}" data-remote="true">-->
                    <!--                    <input id="firstName" class="form-control" type="text" placeholder="Name" name="firstName">-->
                    <!--                    <input id="email_signup" class="form-control" type="text" placeholder="Email" name="email">-->
                    <!--                    <input id="password1" class="form-control" type="password" placeholder="Password" name="password1">-->
                    <!--                    <input id="password2" class="form-control" type="password" placeholder="Repeat Password" name="password2">-->
                    <!--                    <label class="captcha-answer" for="captcha-answer"> Solve: {{ num1 }} + {{ num2 }} = </label>-->
                    <!--                    <input id="{{ random_id }}" class="form-control" type="number" placeholder="" name="captcha-answer">-->
                    <!--                    <input class="btn btn-default btn-register" type="button" value="Create account" name="commit" onclick="signupAjax();">-->
                    <!--                </form>-->
                    <!--            </div>-->
                    <!--        </div>-->
                    <!--    </div>-->
                    <!--</div>-->
                    <!-- End of sign-up form content -->

                    <div class="modal-footer">
                        <div class="forgot login-footer">
                            <span>Looking to
                                <a href="https://search.relengine.com/sign-up" target="_blank">create an account</a>
                            ?</span>
                        </div>
                        <!--<div class="forgot register-footer" style="display:none">-->
                        <!--    <span>Already have an account?</span>-->
                        <!--    <a href="javascript: showLoginForm();">Login</a>-->
                        <!--</div>-->
                    </div>
                </div>
            </div>
        </div>
    </div>
    
<script>
  function loginAndHidePopup(formData) {
    fetch("{{ url_for('auth.login_popup') }}", {
      method: "POST",
      body: JSON.stringify(formData)
    })
    .then((response) => response.json())
    .then((data) => {
      if (data.success) {
        // Handle successful login
        alert('Logged in successfully!');
        $('#loginModal').modal('hide'); // Close the popup
        // You can add further logic to update the UI here
      } else {
        // Handle login failure
        shakeModal('Login failed: ' + data.message);
      }
    })
    .catch((error) => {
      console.error('An error occurred:', error);
      shakeModal('An error occurred while processing your request. Please try again.');
    });
  }
</script>





<script type="text/javascript">

        // $(document).ready(function(){
        //     openLoginModal();
        // });
        // Attach the loginAjax function to the form's submit event
$('#loginForm').submit(function(event) {
    event.preventDefault(); // Prevent the default form submission
    loginAjax();
});

    </script>

</body>
</html>

website/templates/navblock.html
            <!--Nav bar     -->
            <nav class="navbar navbar-expand-lg navbar-light bg-white py-3">
                <div class="container px-5">
                    <a class="navbar-brand" href="/">
                        <img class="logo-img" src="{{ url_for('static', filename='assets/logo2.png')}}" alt="Related Engine" width="50%" height="auto" />
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon">☰</span>
                    </button>
                    <div class="d-flex align-items-center">
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="nav nav-pills nav-justified">
                                <li class="nav-item">
                                    <a class="nav-link active" href="/" style="font-size: 12px; padding: 7.5px 0px;">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="https://relengine.com/docHub" target="_blank" rel="noopener noreferrer" style="font-size: 12px; padding: 7.5px 0px;">Doc Hub</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/JobHunt/" style="font-size: 12px; padding: 7.5px 0px;">Job Finder</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/pm/" style="font-size: 12px; padding: 7.5px 0px;">Search PubMed</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/gs/" style="font-size: 12px; padding: 7.5px 0px;">Search Scholar</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/ai/" style="font-size: 12px; padding: 7.5px 0px;">Ai-Powered Search</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/contact" style="font-size: 12px; padding: 7.5px 0px;">Contact</a>
                                </li>
                                <ul class="navbar-nav nav-flex-icons">
                                {% if user.is_authenticated %}
                                    <li class="nav-item">
                                        <a class="nav-link" href="/myprofile" style="color: black; font-size: 12px; padding: 7.5px 0px;"><i class="fas fa-user"></i> Profile</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="/logout" style="color: black; font-size: 12px; padding: 7.5px 0px;">
                                            <i class="fas fa-sign-out-alt"></i> Sign Out
                                        </a>
                                    </li>
                                {% else %}
                                    <li class="nav-item">
                                        <a class="nav-link" href="/login" style="color: black; font-size: 12px; padding: 7.5px 0px;"><i class="fas fa-sign-in-alt"></i> Login</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="/sign-up" style="color: black; font-size: 12px; padding: 7.5px 0px;"><i class="fas fa-user-plus"></i> Signup</a>
                                    </li>
                                {% endif %}
                                </ul>
                            </ul>
                        </div>
                    </div>
                </div>
            </nav>